In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import openpyxl

## Data Loading

#### The GHG emission data was requested for the European Comission while the population and GDP data was available on the United Nations and World bank Websites, respectively.

In [2]:
EDGAR_FILE = r'C:\Users\indra\Desktop\GitHub\AI Appliction\EDGAR_AR5_GHG_1970_2024.xlsx'
POPULATION_FILE = r'C:\Users\indra\Desktop\GitHub\AI Appliction\Population_with_ISO3.csv'
GDP_ABSOLUTE_FILE = r'C:\Users\indra\Desktop\GitHub\AI Appliction\API_NY.GDP.MKTP.CD_DS2_en_csv_v2_155.csv'

In [3]:
df_ghg = pd.read_excel(EDGAR_FILE, sheet_name='TOTALS BY COUNTRY', skiprows=9)
df_population = pd.read_csv(POPULATION_FILE)
df_gdp_absolute = pd.read_csv(GDP_ABSOLUTE_FILE, skiprows=4)

In [4]:
df_ghg.head()

,IPCC_annex,C_group_IM24_sh,Country_code_A3,Name,Substance,Y_1970,Y_1971,Y_1972,Y_1973,Y_1974,...,Y_2015,Y_2016,Y_2017,Y_2018,Y_2019,Y_2020,Y_2021,Y_2022,Y_2023,Y_2024
0,Non-Annex_I,Rest Central America,ABW,Aruba,GWP_100_AR5_GHG,36.969560,41.825240,52.708352,57.704309,56.999430,...,491.516428,515.073361,496.688325,494.966918,540.013489,519.080727,538.334799,567.492030,569.502788,588.716403
1,Non-Annex_I,India +,AFG,Afghanistan,GWP_100_AR5_GHG,15299.964083,15221.080238,13278.752228,13972.048752,15242.001770,...,28093.084616,27164.741408,30474.594817,31935.810418,32436.168446,32400.167959,32835.845916,31912.139083,32435.106742,33034.840090
2,Non-Annex_I,Southern_Africa,AGO,Angola,GWP_100_AR5_GHG,18834.350180,18721.849826,21316.779023,22878.757106,23586.100827,...,83536.857860,80625.507763,75433.642680,70465.116026,71208.749444,63159.221102,66601.919421,68035.237044,68280.785052,69922.938779
3,Non-Annex_I,Rest Central America,AIA,Anguilla,GWP_100_AR5_GHG,3.397521,3.447974,3.594584,3.480455,3.770682,...,31.417667,31.812681,32.560698,31.682045,31.036684,26.124833,25.313813,25.155856,25.157584,26.035166
4,Int. Aviation,Int. Aviation,AIR,Int. Aviation,GWP_100_AR5_GHG,172478.015810,172465.446718,182459.825527,190296.914796,183162.106070,...,543596.040846,567905.925660,597733.371536,623932.398475,633217.053475,299636.334314,330748.407485,477751.477960,578330.736477,622334.162079

In [5]:
df_ghg.info()

<class 'pandas.DataFrame'>
RangeIndex: 225 entries, 0 to 224
Data columns (total 60 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   IPCC_annex       225 non-null    str
 1   C_group_IM24_sh  225 non-null    str
 2   Country_code_A3  225 non-null    str
 3   Name             225 non-null    str
 4   Substance        225 non-null    str
 5   Y_1970           225 non-null    float64
 6   Y_1971           225 non-null    float64
 7   Y_1972           225 non-null    float64
 8   Y_1973           225 non-null    float64
 9   Y_1974           225 non-null    float64
 10  Y_1975           225 non-null    float64
 11  Y_1976           225 non-null    float64
 12  Y_1977           225 non-null    float64
 13  Y_1978           225 non-null    float64
 14  Y_1979           225 non-null    float64
 15  Y_1980           225 non-null    float64
 16  Y_1981           225 non-null    float64
 17  Y_1982           225 non-null    float64
 18  Y_1983           225 non-null    float64
 19  Y_1984           225 non-null    float64
 20  Y_1985           225 non-null    float64
 21  Y_1986           225 non-null    float64
 22  Y_1987           225 non-null    float64
 23  Y_1988           225 non-null    float64
 24  Y_1989           225 non-null    float64
 25  Y_1990           225 non-null    float64
 26  Y_1991           225 non-null    float64
 27  Y_1992           225 non-null    float64
 28  Y_1993           225 non-null    float64
 29  Y_1994           225 non-null    float64
 30  Y_1995           225 non-null    float64
 31  Y_1996           225 non-null    float64
 32  Y_1997           225 non-null    float64
 33  Y_1998           225 non-null    float64
 34  Y_1999           225 non-null    float64
 35  Y_2000           225 non-null    float64
 36  Y_2001           225 non-null    float64
 37  Y_2002           225 non-null    float64
 38  Y_2003           225 non-null    float64
 39  Y_2004           225 non-null    float64
 40  Y_2005           225 non-null    float64
 41  Y_2006           225 non-null    float64
 42  Y_2007           225 non-null    float64
 43  Y_2008           225 non-null    float64
 44  Y_2009           225 non-null    float64
 45  Y_2010           225 non-null    float64
 46  Y_2011           225 non-null    float64
 47  Y_2012           225 non-null    float64
 48  Y_2013           225 non-null    float64
 49  Y_2014           225 non-null    float64
 50  Y_2015           225 non-null    float64
 51  Y_2016           225 non-null    float64
 52  Y_2017           225 non-null    float64
 53  Y_2018           225 non-null    float64
 54  Y_2019           225 non-null    float64
 55  Y_2020           225 non-null    float64
 56  Y_2021           225 non-null    float64
 57  Y_2022           225 non-null    float64
 58  Y_2023           225 non-null    float64
 59  Y_2024           225 non-null    float64
dtypes: float64(55), str(5)
memory usage: 105.6 KB

In [6]:
df_gdp_absolute.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.983637e+09,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,...,8.318681e+11,9.780765e+11,1.020956e+12,1.018715e+12,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,...,7.000282e+11,6.940513e+11,7.778403e+11,1.026996e+12,9.637847e+11,1.026651e+12,1.063649e+12,9.382384e+11,7.363850e+11,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.987825e+10,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11,NaN

In [7]:
df_gdp_absolute.info()

<class 'pandas.DataFrame'>
RangeIndex: 266 entries, 0 to 265
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    266 non-null    str
 1   Country Code    266 non-null    str
 2   Indicator Name  266 non-null    str
 3   Indicator Code  266 non-null    str
 4   1960            151 non-null    float64
 5   1961            154 non-null    float64
 6   1962            156 non-null    float64
 7   1963            156 non-null    float64
 8   1964            156 non-null    float64
 9   1965            162 non-null    float64
 10  1966            163 non-null    float64
 11  1967            167 non-null    float64
 12  1968            168 non-null    float64
 13  1969            168 non-null    float64
 14  1970            190 non-null    float64
 15  1971            191 non-null    float64
 16  1972            191 non-null    float64
 17  1973            191 non-null    float64
 18  1974            191 non-null    float64
 19  1975            195 non-null    float64
 20  1976            195 non-null    float64
 21  1977            198 non-null    float64
 22  1978            197 non-null    float64
 23  1979            198 non-null    float64
 24  1980            208 non-null    float64
 25  1981            208 non-null    float64
 26  1982            209 non-null    float64
 27  1983            209 non-null    float64
 28  1984            211 non-null    float64
 29  1985            213 non-null    float64
 30  1986            213 non-null    float64
 31  1987            220 non-null    float64
 32  1988            223 non-null    float64
 33  1989            223 non-null    float64
 34  1990            240 non-null    float64
 35  1991            241 non-null    float64
 36  1992            242 non-null    float64
 37  1993            243 non-null    float64
 38  1994            244 non-null    float64
 39  1995            247 non-null    float64
 40  1996            247 non-null    float64
 41  1997            249 non-null    float64
 42  1998            250 non-null    float64
 43  1999            250 non-null    float64
 44  2000            252 non-null    float64
 45  2001            253 non-null    float64
 46  2002            257 non-null    float64
 47  2003            257 non-null    float64
 48  2004            257 non-null    float64
 49  2005            257 non-null    float64
 50  2006            258 non-null    float64
 51  2007            258 non-null    float64
 52  2008            259 non-null    float64
 53  2009            261 non-null    float64
 54  2010            261 non-null    float64
 55  2011            262 non-null    float64
 56  2012            260 non-null    float64
 57  2013            260 non-null    float64
 58  2014            261 non-null    float64
 59  2015            260 non-null    float64
 60  2016            259 non-null    float64
 61  2017            259 non-null    float64
 62  2018            259 non-null    float64
 63  2019            259 non-null    float64
 64  2020            258 non-null    float64
 65  2021            258 non-null    float64
 66  2022            257 non-null    float64
 67  2023            251 non-null    float64
 68  2024            240 non-null    float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 145.6 KB

In [8]:
df_population.head()

  Country/Area  Year     Unit Population ISO3
0  Afghanistan  1970  Persons   11290128  AFG
1  Afghanistan  1971  Persons   11567667  AFG
2  Afghanistan  1972  Persons   11853696  AFG
3  Afghanistan  1973  Persons   12157999  AFG
4  Afghanistan  1974  Persons   12469127  AFG

In [9]:
df_population.info()

<class 'pandas.DataFrame'>
RangeIndex: 12100 entries, 0 to 12099
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country/Area  12100 non-null  str
 1   Year          12100 non-null  int64
 2   Unit          12100 non-null  str
 3   Population    12100 non-null  str
 4   ISO3          11770 non-null  str
dtypes: int64(1), str(4)
memory usage: 472.8 KB

#### The EDGAR GHG emission dataset and the GDP data set are in wide format, while the Population data is already in long format. We will have to make the format consistent and make all the data in long format. The GHG emission data has many columns which a not necessary for our analysis. Also all the datasets have data from the year 1970 but we will only be using the data from 1999 onwards.

## Data Exploration

In [ ]:
common_countries_ISO = set(df_ghg['Country_code_A3']).intersection(set(df_gdp_absolute['Country Code']))
print(common_countries_ISO)

{'PAK', 'LTU', 'ESP', 'MAC', 'MDA', 'SWZ', 'ITA', 'ZAF', 'GBR', 'LUX', 'TKM', 'GNB', 'VIR', 'SLV', 'AGO', 'AFG', 'DMA', 'ERI', 'URY', 'RUS', 'SEN', 'SVN', 'HND', 'MDG', 'CRI', 'PRY', 'MNP', 'LBN', 'CYM', 'DEU', 'MUS', 'PHL', 'GIB', 'FSM', 'LBY', 'FIN', 'DZA', 'BHR', 'ZWE', 'GUM', 'ISL', 'GHA', 'CAF', 'TZA', 'BWA', 'HKG', 'PAN', 'GAB', 'MDV', 'KWT', 'TJK', 'TCD', 'MLT', 'KNA', 'NAM', 'BIH', 'VGB', 'ISR', 'MEX', 'BLR', 'POL', 'NRU', 'DNK', 'PYF', 'MNG', 'NOR', 'FJI', 'ECU', 'SLE', 'CZE', 'CAN', 'VNM', 'FRO', 'NGA', 'IDN', 'MWI', 'BRB', 'LVA', 'ARE', 'IRQ', 'VCT', 'ASM', 'TUR', 'ARM', 'MLI', 'LSO', 'IRL', 'COL', 'SAU', 'GNQ', 'HTI', 'GRD', 'SYC', 'CIV', 'DOM', 'FRA', 'YEM', 'GMB', 'TLS', 'VUT', 'PLW', 'PRK', 'MOZ', 'TTO', 'LKA', 'SWE', 'THA', 'EGY', 'KAZ', 'ZMB', 'SYR', 'MHL', 'ABW', 'LAO', 'PRI', 'QAT', 'ROU', 'BGR', 'UKR', 'ARG', 'CMR', 'BMU', 'GEO', 'GIN', 'USA', 'JPN', 'NPL', 'KEN', 'CPV', 'COM', 'BEN', 'LCA', 'MAR', 'VEN', 'PRT', 'MMR', 'BTN', 'MKD', 'TUV', 'BLZ', 'BOL', 'TGO', 'SVK', 'BRA', 'SDN', 'TUN', 'HRV', 'NZL', 'KGZ', 'COD', 'MYS', 'NIC', 'GTM', 'BHS', 'DJI', 'SGP', 'KIR', 'AZE', 'CHL', 'NER', 'NCL', 'GRC', 'ATG', 'KHM', 'TON', 'JAM', 'RWA', 'GRL', 'SLB', 'SOM', 'AUT', 'BEL', 'ETH', 'LBR', 'WSM', 'UZB', 'BRN', 'UGA', 'AUS', 'JOR', 'COG', 'OMN', 'BFA', 'SUR', 'EST', 'IRN', 'BGD', 'CUB', 'MRT', 'STP', 'KOR', 'CHN', 'HUN', 'BDI', 'GUY', 'ALB', 'PNG', 'TCA', 'NLD', 'CHE', 'CYP', 'PER', 'IND'}

In [11]:
print(df_ghg[df_ghg['Country_code_A3'].isin(common_countries_ISO)]['Name'])

0                     Aruba
1               Afghanistan
2                    Angola
5                   Albania
7      United Arab Emirates
               ...
220                   Samoa
221                   Yemen
222            South Africa
223                  Zambia
224                Zimbabwe
Name: Name, Length: 203, dtype: str

In [12]:
df_gdp_absolute_filtered = df_gdp_absolute[df_gdp_absolute['Country Code'].isin(common_countries_ISO)].reset_index(drop=True)
df_ghg_filtered = df_ghg[df_ghg['Country_code_A3'].isin(common_countries_ISO)].reset_index(drop=True)

In [13]:
df_gdp_absolute_filtered.info()

<class 'pandas.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 70 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Country Name    203 non-null    str
 1   Country Code    203 non-null    str
 2   Indicator Name  203 non-null    str
 3   Indicator Code  203 non-null    str
 4   1960            111 non-null    float64
 5   1961            113 non-null    float64
 6   1962            115 non-null    float64
 7   1963            115 non-null    float64
 8   1964            115 non-null    float64
 9   1965            121 non-null    float64
 10  1966            122 non-null    float64
 11  1967            125 non-null    float64
 12  1968            126 non-null    float64
 13  1969            126 non-null    float64
 14  1970            143 non-null    float64
 15  1971            144 non-null    float64
 16  1972            144 non-null    float64
 17  1973            144 non-null    float64
 18  1974            144 non-null    float64
 19  1975            147 non-null    float64
 20  1976            147 non-null    float64
 21  1977            150 non-null    float64
 22  1978            149 non-null    float64
 23  1979            150 non-null    float64
 24  1980            160 non-null    float64
 25  1981            160 non-null    float64
 26  1982            161 non-null    float64
 27  1983            161 non-null    float64
 28  1984            162 non-null    float64
 29  1985            164 non-null    float64
 30  1986            164 non-null    float64
 31  1987            170 non-null    float64
 32  1988            172 non-null    float64
 33  1989            172 non-null    float64
 34  1990            188 non-null    float64
 35  1991            189 non-null    float64
 36  1992            190 non-null    float64
 37  1993            191 non-null    float64
 38  1994            191 non-null    float64
 39  1995            193 non-null    float64
 40  1996            193 non-null    float64
 41  1997            193 non-null    float64
 42  1998            193 non-null    float64
 43  1999            193 non-null    float64
 44  2000            194 non-null    float64
 45  2001            195 non-null    float64
 46  2002            199 non-null    float64
 47  2003            199 non-null    float64
 48  2004            199 non-null    float64
 49  2005            199 non-null    float64
 50  2006            200 non-null    float64
 51  2007            200 non-null    float64
 52  2008            200 non-null    float64
 53  2009            200 non-null    float64
 54  2010            200 non-null    float64
 55  2011            200 non-null    float64
 56  2012            199 non-null    float64
 57  2013            199 non-null    float64
 58  2014            199 non-null    float64
 59  2015            199 non-null    float64
 60  2016            199 non-null    float64
 61  2017            199 non-null    float64
 62  2018            199 non-null    float64
 63  2019            198 non-null    float64
 64  2020            198 non-null    float64
 65  2021            197 non-null    float64
 66  2022            197 non-null    float64
 67  2023            192 non-null    float64
 68  2024            184 non-null    float64
 69  Unnamed: 69     0 non-null      float64
dtypes: float64(66), str(4)
memory usage: 111.1 KB

In [14]:
df_ghg_filtered.info()

<class 'pandas.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 60 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   IPCC_annex       203 non-null    str
 1   C_group_IM24_sh  203 non-null    str
 2   Country_code_A3  203 non-null    str
 3   Name             203 non-null    str
 4   Substance        203 non-null    str
 5   Y_1970           203 non-null    float64
 6   Y_1971           203 non-null    float64
 7   Y_1972           203 non-null    float64
 8   Y_1973           203 non-null    float64
 9   Y_1974           203 non-null    float64
 10  Y_1975           203 non-null    float64
 11  Y_1976           203 non-null    float64
 12  Y_1977           203 non-null    float64
 13  Y_1978           203 non-null    float64
 14  Y_1979           203 non-null    float64
 15  Y_1980           203 non-null    float64
 16  Y_1981           203 non-null    float64
 17  Y_1982           203 non-null    float64
 18  Y_1983           203 non-null    float64
 19  Y_1984           203 non-null    float64
 20  Y_1985           203 non-null    float64
 21  Y_1986           203 non-null    float64
 22  Y_1987           203 non-null    float64
 23  Y_1988           203 non-null    float64
 24  Y_1989           203 non-null    float64
 25  Y_1990           203 non-null    float64
 26  Y_1991           203 non-null    float64
 27  Y_1992           203 non-null    float64
 28  Y_1993           203 non-null    float64
 29  Y_1994           203 non-null    float64
 30  Y_1995           203 non-null    float64
 31  Y_1996           203 non-null    float64
 32  Y_1997           203 non-null    float64
 33  Y_1998           203 non-null    float64
 34  Y_1999           203 non-null    float64
 35  Y_2000           203 non-null    float64
 36  Y_2001           203 non-null    float64
 37  Y_2002           203 non-null    float64
 38  Y_2003           203 non-null    float64
 39  Y_2004           203 non-null    float64
 40  Y_2005           203 non-null    float64
 41  Y_2006           203 non-null    float64
 42  Y_2007           203 non-null    float64
 43  Y_2008           203 non-null    float64
 44  Y_2009           203 non-null    float64
 45  Y_2010           203 non-null    float64
 46  Y_2011           203 non-null    float64
 47  Y_2012           203 non-null    float64
 48  Y_2013           203 non-null    float64
 49  Y_2014           203 non-null    float64
 50  Y_2015           203 non-null    float64
 51  Y_2016           203 non-null    float64
 52  Y_2017           203 non-null    float64
 53  Y_2018           203 non-null    float64
 54  Y_2019           203 non-null    float64
 55  Y_2020           203 non-null    float64
 56  Y_2021           203 non-null    float64
 57  Y_2022           203 non-null    float64
 58  Y_2023           203 non-null    float64
 59  Y_2024           203 non-null    float64
dtypes: float64(55), str(5)
memory usage: 95.3 KB

#### We are trying to filter the data based on the ISO3 codes. We are doing A intersection B here which will filter the data based on common countries present in both the GHG and GDP dataset.

## Population Dataset Preperation

In [15]:
df_population= df_population[df_population['Year'] >= 1999]
df_population.reset_index(drop=True, inplace=True)

In [16]:
df_population.info()

<class 'pandas.DataFrame'>
RangeIndex: 5720 entries, 0 to 5719
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country/Area  5720 non-null   str
 1   Year          5720 non-null   int64
 2   Unit          5720 non-null   str
 3   Population    5720 non-null   str
 4   ISO3          5564 non-null   str
dtypes: int64(1), str(4)
memory usage: 223.6 KB

In [17]:
df_population.head(40)

   Country/Area  Year     Unit Population ISO3
0   Afghanistan  1999  Persons   19887785  AFG
1   Afghanistan  2000  Persons   20130327  AFG
2   Afghanistan  2001  Persons   20284307  AFG
3   Afghanistan  2002  Persons   21378117  AFG
4   Afghanistan  2003  Persons   22733049  AFG
5   Afghanistan  2004  Persons   23560654  AFG
6   Afghanistan  2005  Persons   24404567  AFG
7   Afghanistan  2006  Persons   25424094  AFG
8   Afghanistan  2007  Persons   25909852  AFG
9   Afghanistan  2008  Persons   26482622  AFG
10  Afghanistan  2009  Persons   27466101  AFG
11  Afghanistan  2010  Persons   28284089  AFG
12  Afghanistan  2011  Persons   29347708  AFG
13  Afghanistan  2012  Persons   30560034  AFG
14  Afghanistan  2013  Persons   31622704  AFG
15  Afghanistan  2014  Persons   32792523  AFG
16  Afghanistan  2015  Persons   33831764  AFG
17  Afghanistan  2016  Persons   34700612  AFG
18  Afghanistan  2017  Persons   35688935  AFG
19  Afghanistan  2018  Persons   36743039  AFG
20  Afghanistan  2019  Persons   37856121  AFG
21  Afghanistan  2020  Persons   39068979  AFG
22  Afghanistan  2021  Persons   40000412  AFG
23  Afghanistan  2022  Persons   40578842  AFG
24  Afghanistan  2023  Persons   41454761  AFG
25  Afghanistan  2024  Persons   42647492  AFG
26      Albania  1999  Persons    3188595  ALB
27      Albania  2000  Persons    3166148  ALB
28      Albania  2001  Persons    3147943  ALB
29      Albania  2002  Persons    3134092  ALB
30      Albania  2003  Persons    3118088  ALB
31      Albania  2004  Persons    3098657  ALB
32      Albania  2005  Persons    3076159  ALB
33      Albania  2006  Persons    3050809  ALB
34      Albania  2007  Persons    3022887  ALB
35      Albania  2008  Persons    2992930  ALB
36      Albania  2009  Persons    2961479  ALB
37      Albania  2010  Persons    2928722  ALB
38      Albania  2011  Persons    2911504  ALB
39      Albania  2012  Persons    2910004  ALB

## Green House Emission Data Prepration

In [18]:
columns_to_keep_in_ghg = ['Country_code_A3','Name', 'Y_1990', 'Y_1992', 'Y_1993', 'Y_1994', 'Y_1995', 'Y_1996', 'Y_1997', 'Y_1998', 'Y_1999', 'Y_2000', 'Y_2001', 'Y_2002', 'Y_2003', 'Y_2004', 'Y_2005', 'Y_2006', 'Y_2007', 'Y_2008', 'Y_2009', 'Y_2010', 'Y_2011', 'Y_2012', 'Y_2013', 'Y_2014', 'Y_2015', 'Y_2016', 'Y_2017', 'Y_2018', 'Y_2019', 'Y_2020', 'Y_2021', 'Y_2022', 'Y_2023', 'Y_2024']
df_ghg_filtered = df_ghg_filtered[columns_to_keep_in_ghg]

In [19]:
df_ghg_filtered.rename(columns={'Country_code_A3':'ISO3','Name': 'Country', 'Y_1990': '1990','Y_1991': '1991', 'Y_1992':'1992', 'Y_1993':'1993', 'Y_1994':'1994', 
                       'Y_1995':'1995', 'Y_1996':'1996', 'Y_1997':'1997', 'Y_1998':'1998', 'Y_1999':'1999', 'Y_2000':'2000', 
                       'Y_2001':'2001', 'Y_2002':'2002', 'Y_2003':'2003', 'Y_2004':'2004', 'Y_2005':'2005', 'Y_2006':'2006', 
                       'Y_2007':'2007', 'Y_2008':'2008', 'Y_2009':'2009', 'Y_2010':'2010', 'Y_2011':'2011', 'Y_2012':'2012', 
                       'Y_2013':'2013', 'Y_2014':'2014', 'Y_2015':'2015', 'Y_2016':'2016', 'Y_2017':'2017', 'Y_2018':'2018',
                         'Y_2019':'2019', 'Y_2020':'2020','Y_2021': '2021','Y_2022': '2022','Y_2023': '2023','Y_2024': '2024'}, inplace=True)
df_ghg_filtered.head()

,ISO3,Country,1990,1992,1993,1994,1995,1996,1997,1998,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,ABW,Aruba,220.317678,272.001133,273.559140,309.068053,338.722132,229.575691,368.721484,377.760443,...,491.516428,515.073361,496.688325,494.966918,540.013489,519.080727,538.334799,567.492030,569.502788,588.716403
1,AFG,Afghanistan,12931.551907,12065.810261,12186.092409,12247.310633,12463.462991,13735.236090,14797.398532,15647.833389,...,28093.084616,27164.741408,30474.594817,31935.810418,32436.168446,32400.167959,32835.845916,31912.139083,32435.106742,33034.840090
2,AGO,Angola,34084.534208,32661.433145,36630.457421,47405.674117,54625.322823,65542.517901,67282.006906,73101.045089,...,83536.857860,80625.507763,75433.642680,70465.116026,71208.749444,63159.221102,66601.919421,68035.237044,68280.785052,69922.938779
3,ALB,Albania,11498.360473,6171.350926,6209.333113,6907.259100,6549.409671,6282.386623,5529.223583,5788.893001,...,8763.343204,8375.388727,9194.657026,9191.052349,8666.245020,7997.195285,8496.282909,7697.618551,7261.247150,7124.310567
4,ARE,United Arab Emirates,79503.672399,87420.939000,94052.920285,98940.663767,103984.524676,109083.857010,110869.288554,111937.192315,...,254207.255480,262189.456758,254267.209100,238779.502432,251893.827917,249749.035983,255352.456728,255592.729579,254307.320721,264148.373742

## GDP Data Prepration

In [20]:
col_to_keep_in_gdp= ['Country Name','Country Code', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
               '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', 
              '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', 
              '2018', '2019', '2020','2021','2022','2023','2024']
df_gdp_absolute = df_gdp_absolute[col_to_keep_in_gdp]
df_gdp_absolute.rename(columns={'Country Name': 'Country', 'Country Code': 'ISO3'}, inplace=True)
df_gdp_absolute.head()

,Country,ISO3,1990,1991,1992,1993,1994,1995,1996,1997,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Aruba,ABW,7.648045e+08,8.720670e+08,9.586592e+08,1.083240e+09,1.245810e+09,1.320670e+09,1.379888e+09,1.531844e+09,...,2.962907e+09,2.983637e+09,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09
1,Africa Eastern and Southern,AFE,2.563831e+11,2.769185e+11,2.411883e+11,2.399812e+11,2.434775e+11,2.733270e+11,2.734276e+11,2.882707e+11,...,9.100020e+11,8.318681e+11,9.780765e+11,1.020956e+12,1.018715e+12,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.913422e+10,1.811657e+10,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN
3,Africa Western and Central,AFW,1.242778e+11,1.307943e+11,1.254494e+11,1.305471e+11,1.353508e+11,2.078439e+11,2.635636e+11,2.764600e+11,...,7.780221e+11,7.000282e+11,6.940513e+11,7.778403e+11,1.026996e+12,9.637847e+11,1.026651e+12,1.063649e+12,9.382384e+11,7.363850e+11
4,Angola,AGO,1.122952e+10,1.060378e+10,8.307811e+09,5.768720e+09,4.438321e+09,5.538749e+09,7.526422e+09,7.648380e+09,...,1.025431e+11,5.987825e+10,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11

## Changing GDP and GHG to long format

## GDP Data in long format from 1990 onwards

In [21]:
#GDP
year_cols_gdp = [col for col in df_gdp_absolute.columns if col.isdigit() and int(col) >= 1990]
df_gdp_long = df_gdp_absolute.melt(
    id_vars=['Country', 'ISO3'],
    value_vars=year_cols_gdp,
    var_name='Year',
    value_name='GDP_USD'
)
df_gdp_long.head()

                       Country ISO3  Year       GDP_USD
0                        Aruba  ABW  1990  7.648045e+08
1  Africa Eastern and Southern  AFE  1990  2.563831e+11
2                  Afghanistan  AFG  1990           NaN
3   Africa Western and Central  AFW  1990  1.242778e+11
4                       Angola  AGO  1990  1.122952e+10

In [22]:
df_gdp_long= df_gdp_long.sort_values(by=['Country','Year']).reset_index(drop=True)
df_gdp_long.head(50)

                        Country ISO3  Year       GDP_USD
0                   Afghanistan  AFG  1990           NaN
1                   Afghanistan  AFG  1991           NaN
2                   Afghanistan  AFG  1992           NaN
3                   Afghanistan  AFG  1993           NaN
4                   Afghanistan  AFG  1994           NaN
5                   Afghanistan  AFG  1995           NaN
6                   Afghanistan  AFG  1996           NaN
7                   Afghanistan  AFG  1997           NaN
8                   Afghanistan  AFG  1998           NaN
9                   Afghanistan  AFG  1999           NaN
10                  Afghanistan  AFG  2000  3.521418e+09
11                  Afghanistan  AFG  2001  2.813572e+09
12                  Afghanistan  AFG  2002  3.825701e+09
13                  Afghanistan  AFG  2003  4.520947e+09
14                  Afghanistan  AFG  2004  5.224897e+09
15                  Afghanistan  AFG  2005  6.203257e+09
16                  Afghanistan  AFG  2006  6.971758e+09
17                  Afghanistan  AFG  2007  9.747886e+09
18                  Afghanistan  AFG  2008  1.010930e+10
19                  Afghanistan  AFG  2009  1.241615e+10
20                  Afghanistan  AFG  2010  1.585667e+10
21                  Afghanistan  AFG  2011  1.780510e+10
22                  Afghanistan  AFG  2012  1.990733e+10
23                  Afghanistan  AFG  2013  2.014642e+10
24                  Afghanistan  AFG  2014  2.049713e+10
25                  Afghanistan  AFG  2015  1.913422e+10
26                  Afghanistan  AFG  2016  1.811657e+10
27                  Afghanistan  AFG  2017  1.875346e+10
28                  Afghanistan  AFG  2018  1.805322e+10
29                  Afghanistan  AFG  2019  1.879944e+10
30                  Afghanistan  AFG  2020  1.995593e+10
31                  Afghanistan  AFG  2021  1.426000e+10
32                  Afghanistan  AFG  2022  1.449724e+10
33                  Afghanistan  AFG  2023  1.715223e+10
34                  Afghanistan  AFG  2024           NaN
35  Africa Eastern and Southern  AFE  1990  2.563831e+11
36  Africa Eastern and Southern  AFE  1991  2.769185e+11
37  Africa Eastern and Southern  AFE  1992  2.411883e+11
38  Africa Eastern and Southern  AFE  1993  2.399812e+11
39  Africa Eastern and Southern  AFE  1994  2.434775e+11
40  Africa Eastern and Southern  AFE  1995  2.733270e+11
41  Africa Eastern and Southern  AFE  1996  2.734276e+11
42  Africa Eastern and Southern  AFE  1997  2.882707e+11
43  Africa Eastern and Southern  AFE  1998  2.687281e+11
44  Africa Eastern and Southern  AFE  1999  2.653210e+11
45  Africa Eastern and Southern  AFE  2000  2.870420e+11
46  Africa Eastern and Southern  AFE  2001  2.608500e+11
47  Africa Eastern and Southern  AFE  2002  2.697460e+11
48  Africa Eastern and Southern  AFE  2003  3.581161e+11
49  Africa Eastern and Southern  AFE  2004  4.459748e+11

## GHG Data in long format from 1990 onwards

In [23]:
#GHG
year_cols_ghg = [col for col in df_ghg_filtered.columns if col.isdigit() and int(col) >= 1990]
df_ghg_long = df_ghg_filtered.melt(
    id_vars=['Country', 'ISO3'],
    value_vars=year_cols_ghg,
    var_name='Year',
    value_name='GHG_Emissions'
)
df_ghg_long.head(100)

                 Country ISO3  Year  GHG_Emissions
0                  Aruba  ABW  1990     220.317678
1            Afghanistan  AFG  1990   12931.551907
2                 Angola  AGO  1990   34084.534208
3                Albania  ALB  1990   11498.360473
4   United Arab Emirates  ARE  1990   79503.672399
..                   ...  ...   ...            ...
95            Kazakhstan  KAZ  1990  342267.891175
96                 Kenya  KEN  1990   38457.802833
97            Kyrgyzstan  KGZ  1990   33367.347720
98              Cambodia  KHM  1990   14577.033668
99              Kiribati  KIR  1990      33.065252

[100 rows x 4 columns]

In [24]:
df_ghg_long= df_ghg_long.sort_values(by=['Country','Year']).reset_index(drop=True)
df_ghg_long.head(100)

        Country ISO3  Year  GHG_Emissions
0   Afghanistan  AFG  1990   12931.551907
1   Afghanistan  AFG  1992   12065.810261
2   Afghanistan  AFG  1993   12186.092409
3   Afghanistan  AFG  1994   12247.310633
4   Afghanistan  AFG  1995   12463.462991
..          ...  ...   ...            ...
95      Algeria  DZA  2018  240580.588744
96      Algeria  DZA  2019  247089.929223
97      Algeria  DZA  2020  233831.050055
98      Algeria  DZA  2021  245876.220983
99      Algeria  DZA  2022  255863.348010

[100 rows x 4 columns]

In [25]:
df_ghg_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 6902 entries, 0 to 6901
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country        6902 non-null   str
 1   ISO3           6902 non-null   str
 2   Year           6902 non-null   str
 3   GHG_Emissions  6902 non-null   float64
dtypes: float64(1), str(3)
memory usage: 215.8 KB

In [26]:
df_gdp_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 9310 entries, 0 to 9309
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  9310 non-null   str
 1   ISO3     9310 non-null   str
 2   Year     9310 non-null   str
 3   GDP_USD  8886 non-null   float64
dtypes: float64(1), str(3)
memory usage: 291.1 KB

## Population data

In [27]:
df_population.rename(columns={'Country/Area': 'Country'}, inplace=True)

In [28]:
df_population[df_population['Country']== "Yemen: Former Democratic Yemen"]

                             Country  Year Unit Population ISO3
5616  Yemen: Former Democratic Yemen  1999  ...        ...  YEM
5617  Yemen: Former Democratic Yemen  2000  ...        ...  YEM
5618  Yemen: Former Democratic Yemen  2001  ...        ...  YEM
5619  Yemen: Former Democratic Yemen  2002  ...        ...  YEM
5620  Yemen: Former Democratic Yemen  2003  ...        ...  YEM
5621  Yemen: Former Democratic Yemen  2004  ...        ...  YEM
5622  Yemen: Former Democratic Yemen  2005  ...        ...  YEM
5623  Yemen: Former Democratic Yemen  2006  ...        ...  YEM
5624  Yemen: Former Democratic Yemen  2007  ...        ...  YEM
5625  Yemen: Former Democratic Yemen  2008  ...        ...  YEM
5626  Yemen: Former Democratic Yemen  2009  ...        ...  YEM
5627  Yemen: Former Democratic Yemen  2010  ...        ...  YEM
5628  Yemen: Former Democratic Yemen  2011  ...        ...  YEM
5629  Yemen: Former Democratic Yemen  2012  ...        ...  YEM
5630  Yemen: Former Democratic Yemen  2013  ...        ...  YEM
5631  Yemen: Former Democratic Yemen  2014  ...        ...  YEM
5632  Yemen: Former Democratic Yemen  2015  ...        ...  YEM
5633  Yemen: Former Democratic Yemen  2016  ...        ...  YEM
5634  Yemen: Former Democratic Yemen  2017  ...        ...  YEM
5635  Yemen: Former Democratic Yemen  2018  ...        ...  YEM
5636  Yemen: Former Democratic Yemen  2019  ...        ...  YEM
5637  Yemen: Former Democratic Yemen  2020  ...        ...  YEM
5638  Yemen: Former Democratic Yemen  2021  ...        ...  YEM
5639  Yemen: Former Democratic Yemen  2022  ...        ...  YEM
5640  Yemen: Former Democratic Yemen  2023  ...        ...  YEM
5641  Yemen: Former Democratic Yemen  2024  ...        ...  YEM

In [29]:
df_population = df_population[(df_population['Country'] != "Yemen: Former Yemen Arab Republic")& (df_population['Country'] != "Yemen: Former Democratic Yemen")]

In [30]:
df_population.info()

<class 'pandas.DataFrame'>
Index: 5668 entries, 0 to 5719
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Country     5668 non-null   str
 1   Year        5668 non-null   int64
 2   Unit        5668 non-null   str
 3   Population  5668 non-null   str
 4   ISO3        5512 non-null   str
dtypes: int64(1), str(4)
memory usage: 265.7 KB

### changing population to int and year to string

In [31]:
df_population['Year'] = df_population['Year'].astype(str)
df_population.info()

<class 'pandas.DataFrame'>
Index: 5668 entries, 0 to 5719
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Country     5668 non-null   str
 1   Year        5668 non-null   str
 2   Unit        5668 non-null   str
 3   Population  5668 non-null   str
 4   ISO3        5512 non-null   str
dtypes: str(5)
memory usage: 265.7 KB

In [32]:
df_population.head()

       Country  Year     Unit Population ISO3
0  Afghanistan  1999  Persons   19887785  AFG
1  Afghanistan  2000  Persons   20130327  AFG
2  Afghanistan  2001  Persons   20284307  AFG
3  Afghanistan  2002  Persons   21378117  AFG
4  Afghanistan  2003  Persons   22733049  AFG

In [33]:
df_population.rename(columns={'Country Name': 'Country'}, inplace=True)

In [34]:
df_population[df_population['ISO3']== "CHN"]

               Country  Year     Unit  Population ISO3
1040  China (mainland)  1999  Persons  1260176655  CHN
1041  China (mainland)  2000  Persons  1269581175  CHN
1042  China (mainland)  2001  Persons  1278725063  CHN
1043  China (mainland)  2002  Persons  1286866839  CHN
1044  China (mainland)  2003  Persons  1294517326  CHN
1045  China (mainland)  2004  Persons  1302100316  CHN
1046  China (mainland)  2005  Persons  1310027136  CHN
1047  China (mainland)  2006  Persons  1318054036  CHN
1048  China (mainland)  2007  Persons  1325813582  CHN
1049  China (mainland)  2008  Persons  1333821016  CHN
1050  China (mainland)  2009  Persons  1342522716  CHN
1051  China (mainland)  2010  Persons  1351561514  CHN
1052  China (mainland)  2011  Persons  1360250664  CHN
1053  China (mainland)  2012  Persons  1369520864  CHN
1054  China (mainland)  2013  Persons  1379008040  CHN
1055  China (mainland)  2014  Persons  1387951972  CHN
1056  China (mainland)  2015  Persons  1396134174  CHN
1057  China (mainland)  2016  Persons  1404052632  CHN
1058  China (mainland)  2017  Persons  1412354727  CHN
1059  China (mainland)  2018  Persons  1419008956  CHN
1060  China (mainland)  2019  Persons  1423520357  CHN
1061  China (mainland)  2020  Persons  1426106093  CHN
1062  China (mainland)  2021  Persons  1426437267  CHN
1063  China (mainland)  2022  Persons  1425179569  CHN
1064  China (mainland)  2023  Persons  1422584933  CHN
1065  China (mainland)  2024  Persons  1419321278  CHN

## GHG and GDP  Dataset merge

### The dataframe of GHG emission and GDP which was converted to long format has been merged using 'inner join' based on the ISO3 code, year and Country.

In [35]:
test_merge =df_ghg_long.merge(df_gdp_long, on=['ISO3', 'Year','Country'], how='inner')

In [36]:
test_merge.info()

<class 'pandas.DataFrame'>
RangeIndex: 5848 entries, 0 to 5847
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country        5848 non-null   str
 1   ISO3           5848 non-null   str
 2   Year           5848 non-null   str
 3   GHG_Emissions  5848 non-null   float64
 4   GDP_USD        5702 non-null   float64
dtypes: float64(2), str(3)
memory usage: 228.6 KB

In [37]:
test_merge.head()

       Country ISO3  Year  GHG_Emissions  GDP_USD
0  Afghanistan  AFG  1990   12931.551907      NaN
1  Afghanistan  AFG  1992   12065.810261      NaN
2  Afghanistan  AFG  1993   12186.092409      NaN
3  Afghanistan  AFG  1994   12247.310633      NaN
4  Afghanistan  AFG  1995   12463.462991      NaN

In [38]:
test_merge[test_merge['ISO3'] == "CHN"]

     Country ISO3  Year  GHG_Emissions       GDP_USD
1224   China  CHN  1990   3.712744e+06  3.615602e+11
1225   China  CHN  1992   3.965077e+06  4.285024e+11
1226   China  CHN  1993   4.171736e+06  4.465573e+11
1227   China  CHN  1994   4.354601e+06  5.669295e+11
1228   China  CHN  1995   4.762328e+06  7.381909e+11
1229   China  CHN  1996   4.771004e+06  8.685239e+11
1230   China  CHN  1997   4.794633e+06  9.677536e+11
1231   China  CHN  1998   4.898209e+06  1.037134e+12
1232   China  CHN  1999   4.850392e+06  1.103843e+12
1233   China  CHN  2000   5.063892e+06  1.223755e+12
1234   China  CHN  2001   5.255074e+06  1.355037e+12
1235   China  CHN  2002   5.584831e+06  1.489822e+12
1236   China  CHN  2003   6.292885e+06  1.683903e+12
1237   China  CHN  2004   7.131534e+06  1.984197e+12
1238   China  CHN  2005   7.974396e+06  2.317551e+12
1239   China  CHN  2006   8.759339e+06  2.791498e+12
1240   China  CHN  2007   9.356343e+06  3.604056e+12
1241   China  CHN  2008   9.576296e+06  4.667346e+12
1242   China  CHN  2009   1.019687e+07  5.189577e+12
1243   China  CHN  2010   1.106204e+07  6.192565e+12
1244   China  CHN  2011   1.205681e+07  7.671757e+12
1245   China  CHN  2012   1.241957e+07  8.673665e+12
1246   China  CHN  2013   1.294861e+07  9.743124e+12
1247   China  CHN  2014   1.309520e+07  1.067453e+13
1248   China  CHN  2015   1.293104e+07  1.128081e+13
1249   China  CHN  2016   1.291309e+07  1.145602e+13
1250   China  CHN  2017   1.316059e+07  1.253756e+13
1251   China  CHN  2018   1.374093e+07  1.414777e+13
1252   China  CHN  2019   1.405286e+07  1.456017e+13
1253   China  CHN  2020   1.423023e+07  1.499641e+13
1254   China  CHN  2021   1.486649e+07  1.820170e+13
1255   China  CHN  2022   1.485740e+07  1.831677e+13
1256   China  CHN  2023   1.541178e+07  1.827036e+13
1257   China  CHN  2024   1.553612e+07  1.874380e+13

## Merging with population dataset

In [39]:
population_test = df_population.copy()

In [40]:
test_merge_final = test_merge.merge(population_test, on=['ISO3', 'Year'], how='inner')

In [41]:
test_merge_final.head()

,Country_x,ISO3,Year,GHG_Emissions,GDP_USD,Country_y,Unit,Population
0,Afghanistan,AFG,1999,16508.477865,NaN,Afghanistan,Persons,19887785
1,Afghanistan,AFG,2000,14364.940472,3.521418e+09,Afghanistan,Persons,20130327
2,Afghanistan,AFG,2001,12628.446200,2.813572e+09,Afghanistan,Persons,20284307
3,Afghanistan,AFG,2002,15228.571950,3.825701e+09,Afghanistan,Persons,21378117
4,Afghanistan,AFG,2003,15857.564957,4.520947e+09,Afghanistan,Persons,22733049

In [42]:
test_merge_final.dtypes

Country_x            str
ISO3                 str
Year                 str
GHG_Emissions    float64
GDP_USD          float64
Country_y            str
Unit                 str
Population           str
dtype: object

In [43]:
test_merge_final.info()

<class 'pandas.DataFrame'>
RangeIndex: 4342 entries, 0 to 4341
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country_x      4342 non-null   str
 1   ISO3           4342 non-null   str
 2   Year           4342 non-null   str
 3   GHG_Emissions  4342 non-null   float64
 4   GDP_USD        4305 non-null   float64
 5   Country_y      4342 non-null   str
 6   Unit           4342 non-null   str
 7   Population     4342 non-null   str
dtypes: float64(2), str(6)
memory usage: 271.5 KB

In [44]:
test_merge_final[(test_merge_final['ISO3'] == "CHN")]

,Country_x,ISO3,Year,GHG_Emissions,GDP_USD,Country_y,Unit,Population
910,China,CHN,1999,4.850392e+06,1.103843e+12,China (mainland),Persons,1260176655
911,China,CHN,2000,5.063892e+06,1.223755e+12,China (mainland),Persons,1269581175
912,China,CHN,2001,5.255074e+06,1.355037e+12,China (mainland),Persons,1278725063
913,China,CHN,2002,5.584831e+06,1.489822e+12,China (mainland),Persons,1286866839
914,China,CHN,2003,6.292885e+06,1.683903e+12,China (mainland),Persons,1294517326
915,China,CHN,2004,7.131534e+06,1.984197e+12,China (mainland),Persons,1302100316
916,China,CHN,2005,7.974396e+06,2.317551e+12,China (mainland),Persons,1310027136
917,China,CHN,2006,8.759339e+06,2.791498e+12,China (mainland),Persons,1318054036
918,China,CHN,2007,9.356343e+06,3.604056e+12,China (mainland),Persons,1325813582
919,China,CHN,2008,9.576296e+06,4.667346e+12,China (mainland),Persons,1333821016
920,China,CHN,2009,1.019687e+07,5.189577e+12,China (mainland),Persons,1342522716
921,China,CHN,2010,1.106204e+07,6.192565e+12,China (mainland),Persons,1351561514
922,China,CHN,2011,1.205681e+07,7.671757e+12,China (mainland),Persons,1360250664
923,China,CHN,2012,1.241957e+07,8.673665e+12,China (mainland),Persons,1369520864
924,China,CHN,2013,1.294861e+07,9.743124e+12,China (mainland),Persons,1379008040
925,China,CHN,2014,1.309520e+07,1.067453e+13,China (mainland),Persons,1387951972
926,China,CHN,2015,1.293104e+07,1.128081e+13,China (mainland),Persons,1396134174
927,China,CHN,2016,1.291309e+07,1.145602e+13,China (mainland),Persons,1404052632
928,China,CHN,2017,1.316059e+07,1.253756e+13,China (mainland),Persons,1412354727
929,China,CHN,2018,1.374093e+07,1.414777e+13,China (mainland),Persons,1419008956
930,China,CHN,2019,1.405286e+07,1.456017e+13,China (mainland),Persons,1423520357
931,China,CHN,2020,1.423023e+07,1.499641e+13,China (mainland),Persons,1426106093
932,China,CHN,2021,1.486649e+07,1.820170e+13,China (mainland),Persons,1426437267
933,China,CHN,2022,1.485740e+07,1.831677e+13,China (mainland),Persons,1425179569
934,China,CHN,2023,1.541178e+07,1.827036e+13,China (mainland),Persons,1422584933
935,China,CHN,2024,1.553612e+07,1.874380e+13,China (mainland),Persons,1419321278

In [45]:
print(test_merge_final.isna().sum())

Country_x         0
ISO3              0
Year              0
GHG_Emissions     0
GDP_USD          37
Country_y         0
Unit              0
Population        0
dtype: int64

In [46]:
rows_with_nan = test_merge_final[test_merge_final.isnull().any(axis=1)]

print(f"Total rows with NaN: {len(rows_with_nan):,}")

Total rows with NaN: 37

In [47]:
test_merge_final.to_csv('C:\\Users\\indra\\Desktop\\GitHub\\AI Appliction\\final_merged_data.csv', index=False)

## The final merged dataset of GHG emission, GDP and population from the year 1999 onwards was save as .csv file for the next step of EDA and Feature Engineering.